### ISSUE TITLE
feat: Allow users to specify output type and encrypt value

### ISSUE THREAD

**Issue by aballiet** [kestra-io/libs#5]
Currently there is no way to output a secret value from a python script.

Users could use Python script to retrieve token value (like a temporary GitHub or any external system) not handled by plugins.

Implementation could look like : 

```YAML
Kestra.outputs({
  myOutput: {
    type: "io.kestra.datatype:aes_encrypted",
    value: "yourAESEncryptedValue"
  }
})
```

In order to encrypt, an `encrypt` function should be available, similar to the pebble one
